#!/bin/bash
#
# Builds the Salus app scheme for the iOS Simulator. CI and humans call this
# same script.
#
# `generic/platform=iOS Simulator` is chosen over a named device on purpose:
# it resolves to the SDK rather than to a booted simulator, so the command
# needs no `iPhone 17 Pro` (or any other device) to exist. The set of installed
# simulators differs between this machine and the GitHub runner image, and it
# changes every time either one updates Xcode; a named destination would make
# the workflow break on an image bump for no reason. Build-only needs no
# device, so nothing is lost. A named destination becomes necessary only when
# `test` is added here (UI/unit tests must actually boot a simulator) — at that
# point pick the device from `xcodebuild -showdestinations` at runtime rather
# than hardcoding one.
#
# Salus.xcodeproj is generated by XcodeGen from project.yml but is COMMITTED,
# so CI builds the committed project and needs no xcodegen on the runner (the
# GitHub macOS image does not ship it). The trade-off is that a project.yml
# edit without a regenerate would go unnoticed here; regenerating in CI and
# diffing was rejected because XcodeGen's output is not byte-stable across
# versions, which would make the job fail on a brew upgrade rather than on a
# real problem.
#
# No `-derivedDataPath` and no beautifier (xcbeautify/xcpretty): the command is
# kept identical to what a developer can paste into a terminal, so a green
# local run means the same command passed.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "==> xcodebuild build (generic iOS Simulator)"
xcodebuild \
    -project Salus.xcodeproj \
    -scheme Salus \
    -destination 'generic/platform=iOS Simulator' \
    build
